services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: ./web
          target: /src/web
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    container_name: local-library_app
    restart: unless-stopped
    command: /entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "80:8000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - django

  db:
    image: postgres:15-alpine
    container_name: local-library_db
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - django

networks:
  django:
    driver: bridge

volumes:
  dbdata:
