# Generated by Django 3.2.13 on 2023-06-20 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('create_author', 'Ajouter un nouvel auteur'),)},
        ),
    ]
