# Generated by Django 3.2.13 on 2023-06-27 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_permission'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back']},
        ),
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': (('edit_and_delete_authors_books', 'Modifier et supprimer un livre ou un auteur.'), ('read_authors_and_books', 'Accès au listing des auteurs et des livres.'), ('create_new_entry', 'Ajouter une nouvelle entrée.'))},
        ),
    ]
