# Generated by Django 3.2.13 on 2023-07-01 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_bookinstance_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.author'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Problème sur document'), ('o', 'Emprunté'), ('a', 'Disponible'), ('r', 'Réservé')], default='m', help_text='Book availability', max_length=1),
        ),
    ]
