# Generated by Django 5.1.3 on 2024-11-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20230701_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='book_pdfs/'),
        ),
    ]
