# Generated by Django 5.1.3 on 2024-11-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_bookinstance_pdf_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='bookmark',
            field=models.IntegerField(default=1),
        ),
    ]
