# Generated by Django 5.1.3 on 2024-11-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_bookinstance_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinstance',
            name='due_back_extension',
            field=models.IntegerField(default=0),
        ),
    ]
